USE TESTDB;
GO

CREATE TABLE Konto (ID int, Saldo int);
INSERT INTO Konto VALUES (1, 100);

-- RCSI auf Datenbank aktivieren (fiktiver Name)
ALTER DATABASE TestDB SET ALLOW_SNAPSHOT_ISOLATION ON;
--SNAPSHOT aktivieren
ALTER DATABASE TestDB SET READ_COMMITTED_SNAPSHOT ON;

